# Form implementation generated from reading ui file 'UI/Multiwfn_Gui_Pushbutton.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Multiwfn_Pushbutton(object):
    def setupUi(self, Multiwfn_Pushbutton):
        Multiwfn_Pushbutton.setObjectName("Multiwfn_Pushbutton")
        Multiwfn_Pushbutton.resize(104, 25)
        Multiwfn_Pushbutton.setStyleSheet("color: #DCDCDC; \n"
"                                      background-color: #1E1E1E;\n"
"                                      font: 10pt \"Consolas\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Multiwfn_Pushbutton)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=Multiwfn_Pushbutton)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton.setStyleSheet("background-color: rgb(60, 63, 65);\n"
"text-align: left;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Multiwfn_Pushbutton)
        QtCore.QMetaObject.connectSlotsByName(Multiwfn_Pushbutton)

    def retranslateUi(self, Multiwfn_Pushbutton):
        _translate = QtCore.QCoreApplication.translate
        Multiwfn_Pushbutton.setWindowTitle(_translate("Multiwfn_Pushbutton", "Form"))
        self.pushButton.setText(_translate("Multiwfn_Pushbutton", "Launch GView"))
